name       : flatpak-kcm
version    : 5.27.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.27.5/flatpak-kcm-5.27.5.tar.xz : 7b7541780654c1007ff268c8e0460def4aa7a58360550410a57531cb0e45ba9a
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Flatpak Permissions Management KCM
description: |
    Flatpak Permissions Management KCM
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(flatpak)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdeclarative-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/flatpak-discover.svg $installdir/usr/share/icons/hicolor/scalable/apps/flatpak-discover.svg
